---
title: "Practical Machine Learning Project"
author: "J.E.Black"
date: "July 21, 2016"
output: html_document
---

## Executive Summary


## Background
Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. 
These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. 
One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. 

Our goal is to use data from accelerometers on the belt, forearm, arm, and dumbell of six  participants. 
Each was asked to perform barbell lifts correctly and incorrectly in five different ways. 


## Exploratory Data Analysis

We acknowledge and thank the group who present their research on the website at: 
http://groupware.les.inf.puc-rio.br/har, 
from which we obtained the the data used in our analysis.
They have been very generous in allowing us to use their data.

- The training data used are are available from: 
"https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"

- The test data are available from: 
"https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"

We quote the authors' description of the data:

```
Six young health participants were asked to perform one set of 10 repetitions of the Unilateral Dumbbell Biceps Curl in five different fashions: exactly according to the specification (Class A), throwing the elbows to the front (Class B), lifting the dumbbell only halfway (Class C), lowering the dumbbell only halfway (Class D) and throwing the hips to the front (Class E).

Class A corresponds to the specified execution of the exercise, while the other 4 classes correspond to common mistakes. Participants were supervised by an experienced weight lifter to make sure the execution complied to the manner they were supposed to simulate. The exercises were performed by six male participants aged between 20-28 years, with little weight lifting experience. We made sure that all participants could easily simulate the mistakes in a safe and controlled manner by using a relatively light dumbbell (1.25kg).
```
Read more: http://groupware.les.inf.puc-rio.br/har#ixzz4F6NogDKh


### Preparation


 




